### ISSUE TITLE
mkl-fft==1.1.0 mkl-random==1.1.1 mkl-service==2.3.0

### ISSUE THREAD

**Issue by python-faker** [marmotlab/PRIMAL2#1]
input
```
pip install -r requirements.txt
```

output
```
ERROR: Could not find a version that satisfies the requirement mkl-fft==1.1.0 (from versions: 1.0.0.17, 1.0.2, 1.0.6)
ERROR: No matching distribution found for mkl-fft==1.1.0
```

when i use conda ,it sloved.

**Comment by GilesLuo** [comment]
Hi,
mkl-fft is a packaged designed for INTEL CPU. It is usually auto-installed in your python environment.
Pls double check that the default pip is pip3, otherwise I think you are using pip2, which is not capable with PRIMAL2.
1. Pls check first whether your machine has a capable CPU that supports mlk.
2. Skip mkl in the requirement, and do 'pip3 install mkl-fft' separately.

If the above-mentioned procedure still fails to work, pls indicate your hardware and contact us. 
Thanks!

Zhiyao

**Comment by hzzzzjzyq** [comment]
python version is 3.4or3.6?
