### ISSUE TITLE
hellow！i have a issues，Does this not require GPU?

### ISSUE THREAD

**Issue by python-faker** [marmotlab/PRIMAL2#2]
I noticed that tensorflow version is 1.11.0, and I want to ask if it doesn't require GPU training? Do I not need to install the GPU version of tensorflow?

thank you very much

**Comment by GilesLuo** [comment]
Hi,
To run the code (either testing code or training code), you don't theoretically have to install tensorflow-gpu. 
Remember to use CUDA_VISIBLE_DEVICES=-1 to disable GPU when you run the code.
But still, using GPU is encouraged since training/testing PRIMAL2 might need days even on powerful CPU and GPU (e.g. 2080ti).

Hope that help
Zhiyao

**Comment by python-faker** [comment]
> Hi,
> To run the code (either testing code or training code), you don't theoretically have to install tensorflow-gpu.
> Remember to use CUDA_VISIBLE_DEVICES=-1 to disable GPU when you run the code.
> But still, using GPU is encouraged since training/testing PRIMAL2 might need days even on powerful CPU and GPU (e.g. 2080ti).
> 
> Hope that help
> Zhiyao

thank you so much
